apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: angular-pipeline-run
spec:
  pipelineRef:
    name: pipeline
  workspaces:
    - name: shared-source
      persistentVolumeClaim:
        claimName: shared-source-pvc
