apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tests
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: tests
      image: ahmedyousseff/node-chrome:latest
      script: |
        #!/bin/sh
        set -eux
        cd /workspace/source
        export CHROME_BIN=/usr/bin/chromium-browser
        npm run test
        echo "Tests passed"
